Fix tinycbor include directory
When tinycbor is provided by an external build system (such as required when
git submodules are not supported), the tinycbor headers are placed in a
'tinycbor/' directory:

| #include <tinycbor/cbor.h>

We need to adjust the cbor sources for this directory, which means our
internal dependency needs to be built slightly differently. We copy the
headers to a folder in the build directory, and point the top-level CMake
to this folder.

Fixes build error:

| In file included from cbor_decode_stream.cpp:6:
| cbor_decode_stream.hpp:13:10: fatal error: cbor.h: No such file or directory
|  #include <cbor.h>
|           ^~~~~~~~